import { describe, expect, it } from 'vitest'
import { createAnalysisOrchestrator } from '@/ai/orchestrator'
import { createFakeAnalystProvider } from '@/ai/fake-provider'
import { createDemoCatalog } from '@/core/catalog'
import { getMetric } from '@/core/metrics'
import type { DeterministicAnalyzer } from '@/core/analyzer'
import type { AnalysisResult } from '@/core/contracts'
import { ProviderTimeoutError } from '@/ai/provider'

const plan = { interpretedQuestion: 'q', intent: 'kpi' as const, metricId: 'net_revenue' as const, sql: 'SELECT 1', verificationSql: 'SELECT 1', expectedShape: { kind: 'single_value' as const, valueColumn: 'net_revenue' }, assumptions: [], chart: { kind: 'kpi' as const, y: 'net_revenue' } }
const synthesis = { summary: 'verified', recommendations: [{ priority: 1 as const, action: 'a', evidenceIds: ['query:primary'] }, { priority: 2 as const, action: 'b', evidenceIds: ['query:primary'] }, { priority: 3 as const, action: 'c', evidenceIds: ['query:primary'] }] }
function result(overrides: Partial<AnalysisResult> = {}): AnalysisResult { return { question: 'q', sql: 'SELECT 1', rows: [{ net_revenue: 1 }], evidence: [{ id: 'query:primary', kind: 'query_result', sql: 'SELECT 1', columns: ['net_revenue'], rowCount: 1, rows: [{ net_revenue: 1 }] }], checks: [], trust: { verdict: 'verified', checks: [] }, warnings: [], ...overrides } }
function run(provider = createFakeAnalystProvider({ plans: [plan], syntheses: [synthesis] }), analyzer: DeterministicAnalyzer = { run: async () => result() }) { return { provider, execute: () => createAnalysisOrchestrator({ provider, analyzer }).run({ question: 'q', catalog: createDemoCatalog(), metrics: [getMetric('net_revenue')!] }) } }

describe('orchestrator', () => {
  it('plans, executes deterministic analysis, then synthesizes without altering trust', async () => { const { provider, execute } = run(); const output = await execute(); expect(output.status).toBe('completed'); expect(output.analysis?.trust.verdict).toBe('verified'); expect(provider.calls.map((call) => call.stage)).toEqual(['plan', 'synthesize']); expect(provider.calls[1]?.input).not.toHaveProperty('rows') })
  it('retries retryable planning error once', async () => { const { provider, execute } = run(createFakeAnalystProvider({ plans: [new ProviderTimeoutError(), plan], syntheses: [synthesis] })); await execute(); expect(provider.calls.filter((call) => call.stage === 'plan')).toHaveLength(2) })
  it('does not retry caller abort', async () => { const controller = new AbortController(); controller.abort(); const provider = createFakeAnalystProvider({ plans: [plan] }); await expect(createAnalysisOrchestrator({ provider, analyzer: { run: async () => result() } }).run({ question: 'q', catalog: createDemoCatalog(), metrics: [getMetric('net_revenue')!], signal: controller.signal })).rejects.toThrow(); expect(provider.calls).toHaveLength(0) })
  it('repairs a guard rejection once and fully reruns analyzer', async () => { const rejected = result({ checks: [{ id: 'sql_guard_primary', status: 'fail', severity: 'critical', message: 'unsafe', evidenceIds: [] }] }); let calls = 0; const analyzer: DeterministicAnalyzer = { run: async () => ++calls === 1 ? rejected : result() }; const repaired = { sql: 'SELECT 2', verificationSql: 'SELECT 2', expectedShape: { kind: 'single_value' as const, valueColumn: 'net_revenue' } }; const { provider, execute } = run(createFakeAnalystProvider({ plans: [plan], repairs: [repaired], syntheses: [synthesis] }), analyzer); expect((await execute()).status).toBe('completed'); expect(calls).toBe(2); expect(provider.calls.map((call) => call.stage)).toEqual(['plan', 'repair', 'synthesize']) })
  it('rejects after a second guard failure and skips synthesis', async () => { const rejected = result({ checks: [{ id: 'sql_guard_primary', status: 'fail', severity: 'critical', message: 'unsafe', evidenceIds: [] }] }); const { provider, execute } = run(createFakeAnalystProvider({ plans: [plan], repairs: [{ sql: 'SELECT 2', verificationSql: 'SELECT 2', expectedShape: { kind: 'single_value', valueColumn: 'net_revenue' } }] }), { run: async () => rejected }); expect((await execute()).status).toBe('rejected'); expect(provider.calls.map((call) => call.stage)).toEqual(['plan', 'repair']) })
  it('skips synthesis on primary execution failure', async () => { const failed = result({ checks: [{ id: 'primary_execution', status: 'fail', severity: 'critical', message: 'boom', evidenceIds: [] }] }); const { provider, execute } = run(createFakeAnalystProvider({ plans: [plan] }), { run: async () => failed }); expect((await execute()).status).toBe('failed'); expect(provider.calls.map((call) => call.stage)).toEqual(['plan']) })
  it('preserves analysis and falls back after two synthesis failures', async () => { const { execute } = run(createFakeAnalystProvider({ plans: [plan], syntheses: [new ProviderTimeoutError(), new ProviderTimeoutError()] })); const output = await execute(); expect(output.status).toBe('fallback'); expect(output.analysis?.rows).toEqual([{ net_revenue: 1 }]); expect(output.synthesis?.recommendations).toHaveLength(3) })
})
